# Generated by Django 2.0.2 on 2025-07-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('sex', models.CharField(default='', max_length=255, verbose_name='性别')),
                ('age', models.CharField(default='', max_length=255, verbose_name='年龄')),
                ('career', models.CharField(default='', max_length=255, verbose_name='职业')),
                ('sleep_duration', models.CharField(default='', max_length=255, verbose_name='睡眠时长')),
                ('sleep_quality', models.CharField(default='', max_length=255, verbose_name='睡眠质量')),
                ('physical_activity_level', models.CharField(default='', max_length=255, verbose_name='身体活动水平')),
                ('pressure', models.CharField(default='', max_length=255, verbose_name='压力水平')),
                ('bmi', models.CharField(default='', max_length=255, verbose_name='BMI')),
                ('blood_pressure', models.CharField(default='', max_length=255, verbose_name='血压')),
                ('heart_rate', models.CharField(default='', max_length=255, verbose_name='心率')),
                ('daily_steps', models.CharField(default='', max_length=255, verbose_name='每日步数')),
                ('sleep_disorders', models.CharField(default='', max_length=255, verbose_name='睡眠障碍')),
                ('comments', models.TextField(default='', verbose_name='用户评论')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='爬取时间')),
            ],
            options={
                'verbose_name': '睡眠健康数据表',
                'verbose_name_plural': '睡眠健康数据表',
                'db_table': 'app_health',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('sex', models.CharField(default='', max_length=255, verbose_name='性别')),
                ('address', models.CharField(default='', max_length=255, verbose_name='地址')),
                ('avatar', models.FileField(default='avatar/default.png', upload_to='avatar', verbose_name='头像')),
                ('textarea', models.CharField(default='这个人很懒，什么有没留下。', max_length=255, verbose_name='个人简介')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'app_user',
            },
        ),
    ]
