# Generated by Django 2.0.2 on 2025-07-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default='', max_length=255, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_pressure',
            field=models.CharField(default='', max_length=255, verbose_name='血压'),
        ),
        migrations.AddField(
            model_name='user',
            name='bmi',
            field=models.CharField(default='', max_length=255, verbose_name='BMI'),
        ),
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.CharField(default='', max_length=255, verbose_name='职业'),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_steps',
            field=models.CharField(default='', max_length=255, verbose_name='每日步数'),
        ),
        migrations.AddField(
            model_name='user',
            name='heart_rate',
            field=models.CharField(default='', max_length=255, verbose_name='心率'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=255, verbose_name='电话号码'),
        ),
        migrations.AddField(
            model_name='user',
            name='physical_activity_level',
            field=models.CharField(default='', max_length=255, verbose_name='身体活动水平'),
        ),
        migrations.AddField(
            model_name='user',
            name='pressure',
            field=models.CharField(default='', max_length=255, verbose_name='压力水平'),
        ),
        migrations.AddField(
            model_name='user',
            name='sleep_disorders',
            field=models.CharField(default='', max_length=255, verbose_name='睡眠障碍'),
        ),
        migrations.AddField(
            model_name='user',
            name='sleep_duration',
            field=models.CharField(default='', max_length=255, verbose_name='睡眠时长'),
        ),
        migrations.AddField(
            model_name='user',
            name='sleep_quality',
            field=models.CharField(default='', max_length=255, verbose_name='睡眠质量'),
        ),
    ]
