# Generated by Django 2.0.2 on 2025-07-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250709_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='', max_length=255, verbose_name='公开状态'),
        ),
    ]
