# Generated by Django 2.0.2 on 2025-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.TextField(default='', verbose_name='用户评论'),
        ),
    ]
